src/algorithms/clas12/event_builder_filter/EventBuilderFilter.cc
src/iguana/Iguana.h
src/services/Algorithm.cc
src/services/Algorithm.h
src/tests/main.cc

fix: pass banks by reference

---

src/algorithms/clas12/event_builder_filter/EventBuilderFilter.h
src/algorithms/clas12/lorentz_transformer/LorentzTransformer.cc
src/algorithms/clas12/lorentz_transformer/LorentzTransformer.h
src/iguana/AlgorithmSequence.cc
src/iguana/AlgorithmSequence.h
src/services/Algorithm.cc
src/services/Algorithm.h
src/services/Logger.h
src/services/Object.cc
src/services/Object.h
src/services/meson.build
src/tests/run_banks.cc

Implement `AlgorithmSequence` to run a user's sequence of algorithms.

feat: algorithm sequencing

---

src/services/Algorithm.cc
src/services/Algorithm.h
src/tests/run_banks.cc

This is so users can treat log levels as additional algorithm options.

feat: set log level if option name is `"log"`

---

.github/test-consumer-build.sh
.github/workflows/linux.yml

Prefer "consumer" over "dependent"

style: `test-dependent-build.sh` -> `test-consumer-build.sh`

---

.github/workflows/linux.yml

If we tell users to do this, it's better to test like this.

ci: use python virtual environment for python bindings

---

README.md
src/iguana/algorithms/example/ExampleAlgorithm.cc
src/iguana/algorithms/example/ExampleAlgorithm.h
src/iguana/algorithms/example/README.md
src/iguana/algorithms/example/make_template.sh
src/iguana/algorithms/meson.build

This will allow algorithm developers to get started quickly writing new algorithms.

feat: generate a template algorithm

---

.gitignore
src/iguana/algorithms/AlgorithmBoilerplate.h
src/iguana/algorithms/AlgorithmSequence.cc
src/iguana/algorithms/AlgorithmSequence.h
src/iguana/algorithms/clas12/EventBuilderFilter.cc
src/iguana/algorithms/clas12/EventBuilderFilter.h
src/iguana/algorithms/clas12/LorentzTransformer.cc
src/iguana/algorithms/clas12/LorentzTransformer.h
src/iguana/algorithms/example/ExampleAlgorithm.cc
src/iguana/algorithms/example/ExampleAlgorithm.h

- makes it easier to read the code
- resolve #69

fix: remove `Start`, `Run`, `Stop` preprocessor macros

---

.github/workflows/ci.yml

ci: use main `hipo` fork and latest tag

---

src/iguana/services/ConfigFileManager.cc
src/iguana/services/ConfigFileManager.h

fix: allow config files to be loaded by absolute or relative paths

---

doc/dependency_resolution.md
meson.build
meson/resolve-dependencies.py
meson/this_iguana.sh.in

fix: don't assume `.pc` files are found in `$PREFIX/lib/pkgconfig`

---

doc/namespaces.h
examples/iguana-example-00-basic.cc
examples/iguana-example-01-bank-rows.cc
examples/iguana-example-02-YAMLReader.cc
examples/iguana-example-03-zvertex-filter.cc
src/iguana/algorithms/Algorithm.cc
src/iguana/algorithms/Algorithm.h
src/iguana/algorithms/AlgorithmBoilerplate.h
src/iguana/algorithms/AlgorithmFactory.cc
src/iguana/algorithms/AlgorithmSequence.cc
src/iguana/algorithms/AlgorithmSequence.h
src/iguana/algorithms/clas12/EventBuilderFilter.cc
src/iguana/algorithms/clas12/EventBuilderFilter.h
src/iguana/algorithms/clas12/LorentzTransformer.cc
src/iguana/algorithms/clas12/LorentzTransformer.h
src/iguana/algorithms/clas12/MomentumCorrection.cc
src/iguana/algorithms/clas12/MomentumCorrection.h
src/iguana/algorithms/clas12/ZVertexFilter.cc
src/iguana/algorithms/clas12/ZVertexFilter.h
src/iguana/algorithms/example/ExampleAlgorithm.cc
src/iguana/algorithms/example/ExampleAlgorithm.h
src/iguana/services/ConfigFileReader.cc
src/iguana/services/ConfigFileReader.h
src/iguana/services/Logger.cc
src/iguana/services/Logger.h
src/iguana/services/Object.cc
src/iguana/services/Object.h
src/iguana/services/YAMLReader.cc
src/iguana/services/YAMLReader.h
src/iguana/tests/iguana-test.cc

First usage of #103, while things are still quiet here.

chore: auto format

---

.github/workflows/ci.yml
doc/namespaces.h
meson/ubsan.supp
src/iguana/algorithms/Algorithm.cc
src/iguana/algorithms/Algorithm.h
src/iguana/algorithms/AlgorithmFactory.cc
src/iguana/algorithms/TypeDefs.h
src/iguana/algorithms/clas12/LorentzTransformer.cc
src/iguana/algorithms/clas12/LorentzTransformer.h
src/iguana/algorithms/meson.build
src/iguana/algorithms/physics/InclusiveKinematics.cc
src/iguana/algorithms/physics/InclusiveKinematics.h
src/iguana/algorithms/physics/InclusiveKinematics.yaml
src/iguana/algorithms/physics/InclusiveKinematicsValidator.cc
src/iguana/algorithms/physics/InclusiveKinematicsValidator.h
src/iguana/tests/include/TestValidator.h

feat: calculate inclusive kinematics

---

src/iguana/algorithms/Algorithm.h
src/iguana/services/Logger.cc
src/iguana/tests/iguana-test.cc
src/iguana/tests/include/TestAlgorithm.h
src/iguana/tests/include/TestConfig.h
src/iguana/tests/include/TestLogger.h
src/iguana/tests/meson.build

Improve infrastructure testing coverage.
Diff:

test: increase coverage

---

.clang-format
examples/iguana-example-00-basic.cc
examples/iguana-example-01-bank-rows.cc
src/iguana/algorithms/Algorithm.cc
src/iguana/algorithms/Algorithm.h
src/iguana/algorithms/AlgorithmFactory.cc
src/iguana/algorithms/AlgorithmSequence.cc
src/iguana/algorithms/clas12/EventBuilderFilter.cc
src/iguana/algorithms/clas12/EventBuilderFilter.h
src/iguana/algorithms/clas12/MomentumCorrection.cc
src/iguana/algorithms/clas12/MomentumCorrection.h
src/iguana/algorithms/clas12/MomentumCorrectionValidator.cc
src/iguana/algorithms/clas12/MomentumCorrectionValidator.h
src/iguana/algorithms/clas12/SectorFinder.cc
src/iguana/algorithms/clas12/SectorFinder.h
src/iguana/algorithms/clas12/ZVertexFilter.cc
src/iguana/algorithms/clas12/ZVertexFilter.h
src/iguana/algorithms/example/ExampleAlgorithm.cc
src/iguana/algorithms/example/ExampleAlgorithm.h
src/iguana/algorithms/physics/InclusiveKinematics.cc
src/iguana/algorithms/physics/InclusiveKinematics.h
src/iguana/services/ConfigFileReader.cc
src/iguana/services/Logger.cc
src/iguana/services/Logger.h
src/iguana/services/YAMLReader.cc
src/iguana/tests/include/TestConfig.h
src/iguana/tests/include/TestLogger.h

East `const` makes it clearer _what_ is actually `const`: everything to its left

style: qualifier alignment to east `const`

---

.github/workflows/ci.yml
.gitignore
examples/meson.build
meson.build

fix: dataframe example should not build if `libHipoDataFrame` is not installed

---

.github/workflows/ci.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/minver.yml
bind/python/meson.build
doc/setup.md
examples/README.md
meson.build
meson.options
meson/release/native/release.ini

- Improve option name consistency
- Improve documentation

build!: organize build options

---

meson/resolve-dependencies.py

fix: `resolve-dependencies.py` might find the wrong `.pc` file

---

.github/workflows/ci.yml
src/iguana/tests/meson.build

- adds benchmarks, which may be run with `meson test --benchmark`
- CI reports benchmarks, currently just algorithm execution time

feat: benchmark algorithms

---

.github/auto-format.sh
.github/install-dependency-packages.sh
.github/source-ROOT.sh
doc/setup.md
meson.build
meson/detect-version.sh
meson/minimum-version.sh
meson/release/install-cvmfs.sh
meson/this_iguana.sh.in
meson/this_iguana.tcsh.in
src/iguana/algorithms/example/make_template.sh

Install `this_iguana.tcsh`, which sources `this_iguana.sh` and spawns a new `tcsh` instance.

feat: support `tcsh` environmental setup

---

src/iguana/algorithms/TypeDefs.h

header protection as multiple .h files include this

Fix header guards for TypeDefs.h

---

src/iguana/algorithms/clas12/FTEnergyCorrection/Algorithm.cc
src/iguana/algorithms/clas12/FTEnergyCorrection/Algorithm.h

Just corrects the energy, rather than the `RECFT::Particle` 3-momentum

feat: action function `FTEnergyCorrection::CorrectEnergy`

---

examples/iguana-example-bank-rows.cc
examples/iguana-example-basic.cc

Create readers to only read tag 0 events. This will give a more sensible output

Dglazier patch 1

---

doc/gen/Doxyfile
src/iguana/algorithms/clas12/EventBuilderFilter/Algorithm.h
src/iguana/algorithms/clas12/FTEnergyCorrection/Algorithm.h
src/iguana/algorithms/clas12/LorentzTransformer/Algorithm.h
src/iguana/algorithms/clas12/MomentumCorrection/Algorithm.h
src/iguana/algorithms/clas12/PhotonGBTFilter/Algorithm.h
src/iguana/algorithms/clas12/SectorFinder/Algorithm.h
src/iguana/algorithms/clas12/ZVertexFilter/Algorithm.h
src/iguana/algorithms/example/ExampleAlgorithm/Algorithm.h
src/iguana/algorithms/physics/InclusiveKinematics/Algorithm.h

doc: add algorithm full name to API documentation

---

.github/auto-format.sh
bind/python/meson.build
doc/maintenance.md
examples/meson.build
meson.build
meson.format
src/iguana/algorithms/meson.build
src/iguana/services/meson.build
src/iguana/tests/meson.build

style: `meson` formatting

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/minver.yml

ci: add `workflow_dispatch` trigger

---

src/iguana/tests/iguana_test.cc

Some of the usage guides for commands wasn't printing.

fix: `iguana_test` commands' usage guide

---

src/iguana/algorithms/physics/InclusiveKinematics/Algorithm.cc
src/iguana/algorithms/physics/InclusiveKinematics/Algorithm.h

for consistency with the algorithm's output bank

feat: add `pindex` to `InclusiveKinematicsVars`

---

.github/install-dependency-packages.sh
.github/workflows/ci.yml
meson.build
meson/asan.supp
src/iguana/algorithms/physics/InclusiveKinematics/Algorithm.cc
src/iguana/services/GlobalParam.cc
src/iguana/services/GlobalParam.h
src/iguana/services/Object.cc
src/iguana/services/Object.h
src/iguana/services/RCDBReader.cc
src/iguana/services/RCDBReader.h
subprojects/rcdb/meson.build

If the user has SQLite, it will use that as well for RCDB.

feat: allow for SQLite DBMS for RCDB

---

src/iguana/algorithms/Algorithm.h

warn the brave soul who dares to try again

doc: note about `bool` configuration option issue

---

meson.build
src/iguana/algorithms/Validator.h
src/iguana/algorithms/clas12/FiducialFilter/Validator.cc
src/iguana/algorithms/clas12/MomentumCorrection/Validator.cc
src/iguana/algorithms/clas12/PhotonGBTFilter/Validator.cc
src/iguana/algorithms/clas12/PhotonGBTFilter/Validator.h
src/iguana/algorithms/clas12/SectorFinder/Validator.cc
src/iguana/algorithms/clas12/ZVertexFilter/Validator.cc
src/iguana/algorithms/physics/Depolarization/Validator.cc
src/iguana/algorithms/physics/DihadronKinematics/Validator.cc
src/iguana/algorithms/physics/InclusiveKinematics/Validator.cc
src/iguana/algorithms/physics/SingleHadronKinematics/Validator.cc
src/iguana/tests/meson.build

The default color palette uses yellow as its maximum, which makes it very difficult to see large spikes on a white background.

style: improve 2D plot color palette

---

src/iguana/algorithms/physics/InclusiveKinematics/Algorithm.cc

I've been cross checking Iguana algorithms with my old analysis code, and noticed some algorithm ordering was causing a ~1.5% difference in yields. After discussing with @raffaelladevita, we propose the order:
1. `physics::InclusiveKinematics`: finds electron and calculates inclusive kinematics
a. choose FD trigger electrons
b. select the max-E electron of those
c. this should almost always be `pindex = 0`
d. calculate kinematics
2. `clas12::FiducialFilter`: fiducial cuts
3. check if electron survived fiducial cuts (more motivation for #352)
This PR fixes 1.'s substep ordering, were on `main` we are currently doing 1b. before 1a.

fix: find electron by requiring FD trigger first

---

src/iguana/algorithms/clas12/SectorFinder/Algorithm.h

This enumerator is new; use it in `SectorFinder`.

refactor(`SectorFinder`): use `DetectorType` enumerator

---

src/iguana/algorithms/clas12/ZVertexFilter/Config.yaml

Adjusted electron vertex cuts under ZVertexFilter/Config.yaml for RGA Sp18 Inb, Sp18 Out, Fa18 Inb, Fa18 Out and Sp19 Inb run periods

Updated RGA electron z-vertex cuts

---

src/iguana/algorithms/TypeDefs.h

Respects https://github.com/JeffersonLab/coatjava/pull/784

refactor!: remove unused `DetectorType`s
