install.rb
meson.build
src/algorithms/clas12/fiducial_cuts/meson.build
src/iguana/meson.build
src/services/meson.build
src/tests/meson.build

Some distributions install libraries in `$prefix/lib/x86.../`, whereas others use `$prefix/lib`. This PR enforces `$prefix/lib`, to be consistent with the installation `rpath`; this is a stopgap until I can figure out how to set the installation's `rpath` automatically.

fix: override default install directories for `rpath` consistency

---

meson.build
src/algorithms/clas12/event_builder_filter/EventBuilderFilter.cc
src/algorithms/clas12/event_builder_filter/EventBuilderFilter.h
src/algorithms/clas12/event_builder_filter/README.md
src/algorithms/meson.build
src/iguana/Arbiter.cc
src/iguana/Arbiter.h
src/iguana/meson.build
src/services/Algorithm.cc
src/services/Algorithm.h
src/services/Logger.cc
src/services/Logger.h
src/services/meson.build
src/tests/main.cc

This is the first prototype of `hipo::bank` I/O capabilities, a simple filtering algorithm which removes `REC::Particle` rows that the user does not want.
Resolves #3

feat: add event builder filter algorithm

---

src/iguana/Iguana.cc
src/iguana/Iguana.h
src/iguana/meson.build
src/tests/main.cc

- rename `Arbiter` to `Iguana`
- tried to simplify test example `main.cc` as much as possible
- unfortunately, still have to get the `schema` up front: https://github.com/gavalian/hipo/issues/30
- best we can do for now is organize `main.cc` and add comments

refactor: rename `Arbiter->Iguana` and organize `main.cc`

---

doc/design.md
src/algorithms/clas12/event_builder_filter/EventBuilderFilter.cc
src/algorithms/clas12/event_builder_filter/EventBuilderFilter.h
src/iguana/Iguana.h
src/services/Algorithm.cc
src/services/Algorithm.h
src/services/Logger.cc
src/services/Logger.h
src/services/TypeDefs.h
src/services/meson.build
src/tests/main.cc

- Algorithm `Run` method now operates on a `BankVec`, a `std::vector` of bank pointers
- `Run` now returns `void`; instead it is allowed to mutate the input `BankVec`; this saves some time by avoiding copying banks
- `Start` will set the index of the `BankVec` for each required bank, so `Run` avoids hashing (_cf._ previous design's `BankMap`, an unordered map of bank names to bank pointers, which requires extensive hashing)
- Creator algorithms will need a pointer to the "new" bank in the input `BankVec`
- Algorithms may be initialized one of two ways:
- call `Start()`: a default (algorithm-dependent) ordering of banks will be assumed by `Run`
- call `Start(std::unordered_map<std::string, int> m)`, where `m` provides the index of the `BankVec` for each bank
This design provides …

refactor: use `vector` of banks for algorithm I/O

---

.github/workflows/linux.yml
src/algorithms/clas12/event_builder_filter/EventBuilderFilter.cc
src/algorithms/clas12/event_builder_filter/EventBuilderFilter.h
src/services/Algorithm.h
src/tests/meson.build
src/tests/run_banks.cc
src/tests/run_rows.cc

This allows users to run the filter on each bank row, for compatibility with `chanser` and `clas12root`

feat: expose public `Filter` function in `EventBuilderFilter`

---

.github/workflows/linux.yml
.gitignore
README.md
install.rb
meson.build
meson.options
src/algorithms/clas12/event_builder_filter/EventBuilderFilter.cc
src/algorithms/clas12/event_builder_filter/EventBuilderFilter.h
src/algorithms/meson.build
src/iguana/meson.build
src/services/Algorithm.cc
src/services/Algorithm.h
src/services/Logger.cc
src/services/Logger.h
src/services/TypeDefs.h
src/services/meson.build
src/tests/meson.build
src/tests/run_banks.cc
src/tests/run_rows.cc

The scope of this PR expanded beyond its original intent, and should actually separated into the following PRs:
- cache the option to avoid hashing in `Run`
- set default option values
- provide `SetOption` for the user
- provide `PrintOption` to dump options
- `error` and `warn` log printouts are now colored
- enabled by default, and can be disabled by the user
- use built-in options for better user control

feat+build: improve algorithm configuration; colored log output; improve dependency resolution

---

configure.py

Some installations may still use `python` for v2, or may not even have `python` in `$PATH` and only have `python3`. Using `python3` in the shebang seems to be a common trend for v3 scripts.
Discussion here: https://stackoverflow.com/questions/64048813/what-shebang-should-i-use-to-consistently-point-to-python3
which includes a more robust solution using a "hybrid script" approach:
```python
#!/bin/bash
_='''' # Prefer python3 if it exists
command -v python3 &> /dev/null && exec python3 $0 "$@" || exec python $0 "$@"
'''
print ("Hello")
```
Let's use `python3` unless this becomes an issue.

fix: python shebang `python`->`python3`

---

.github/workflows/linux.yml
src/algorithms/clas12/event_builder_filter/EventBuilderFilter.cc
src/services/Algorithm.cc
src/services/Algorithm.h
src/tests/run_banks.cc
src/tests/run_rows.cc

Since https://github.com/gavalian/hipo/pull/29 was reverted, we are forced to regress some usability here.
Instead of using upstream type inference via
```cpp
bank.get(...)
```
we must use one of
```
bank.getInt(...)
bank.getFloat(...)
// etc.
```
and know the data types at compile time (though the correct type is only verified upstream at runtime).

fix: regress `hipo::bank::get` to `hipo::bank::get[TYPE]`

---

configure.py

Add the dependency names to the generated `ini` file.

build: clarify which paths correspond to which dependencies

---

.github/workflows/linux.yml
doc/Doxyfile
src/algorithms/clas12/event_builder_filter/EventBuilderFilter.h
src/algorithms/clas12/event_builder_filter/README.md
src/algorithms/clas12/fiducial_cuts/README.md
src/algorithms/clas12/lorentz_transformer/LorentzTransformer.cc
src/algorithms/clas12/lorentz_transformer/LorentzTransformer.h
src/algorithms/clas12/momentum_corrections/README.md
src/algorithms/clas12/pid_refinement/README.md
src/algorithms/meson.build
src/iguana/AlgorithmSequence.cc
src/iguana/AlgorithmSequence.h
src/services/Algorithm.h
src/tests/run_banks.cc

Adds a sample "transformer" algorithm. The only transformation added here is momentum inversion, which while not so useful, at least lets us test this type of algorithm.

feat: Lorentz transformer algorithm

---

src/algorithms/AlgorithmFactory.cc
src/algorithms/AlgorithmFactory.h
src/algorithms/AlgorithmSequence.cc
src/algorithms/AlgorithmSequence.h
src/algorithms/clas12/event_builder_filter/EventBuilderFilter.cc
src/algorithms/clas12/event_builder_filter/EventBuilderFilter.h
src/algorithms/clas12/lorentz_transformer/LorentzTransformer.cc
src/algorithms/clas12/lorentz_transformer/LorentzTransformer.h
src/algorithms/meson.build
src/tests/run_banks.cc

To mitigate language bindings, it would be useful to be able to create algorithms by only knowing their `string` names. Since C++ doesn't have reflection, we need some other approach.
Use a factory to create an algorithm on-the-fly. Algorithms only need to self-register with a unique name, which is hard-coded as their class name.
This was done following https://www.cppstories.com/2018/02/factory-selfregister/
- **BEWARE** of a pitfall where `static unordered_map AlgorithmFactory::s_creators` may not exist before it is filled; I think if the linking order is _always_ correct, this shouldn't bite us.
- Details: https://stackoverflow.com/questions/48578226/c-static-initialization-order-adding-into-a-map
- C++20 `constinit` may save us: https://www.cppstories.com/2023/ub-factory-constinit/

feat: factory pattern with self-registration for algorithm creation

---

.github/workflows/linux.yml
bind/python/pyiguana/__init__.py
configure.py
examples/build_with_cmake/CMakeLists.txt
examples/build_with_make/Makefile
examples/build_with_make/README.md
examples/build_with_meson/meson.build
examples/meson.build
meson.build
meson/this_iguana.sh.in

Build configuration is much easier when upstream uses `pkg-config`.
Requires https://github.com/gavalian/hipo/pull/42

build: use `pkg-config` for `hipo4`

---

doc/Doxyfile
src/iguana/algorithms/Algorithm.h
src/iguana/algorithms/AlgorithmBoilerplate.h
src/iguana/algorithms/AlgorithmSequence.cc
src/iguana/algorithms/AlgorithmSequence.h
src/iguana/algorithms/clas12/EventBuilderFilter.cc
src/iguana/algorithms/clas12/EventBuilderFilter.h
src/iguana/algorithms/clas12/LorentzTransformer.cc
src/iguana/algorithms/clas12/LorentzTransformer.h
src/iguana/algorithms/meson.build

To maintain consistency among the algorithms' boilerplate, and to reduce the amount of boilerplate that one needs to write in each algorithm, use preprocessor macros to generate the boilerplate. All macros are defined and documented in `AlgorithmBoilerplate.h`.

feat: generate algorithm boilerplate with preprocessor macros

---

configure.py
doc/troubleshooting.md
src/iguana/algorithms/example/README.md

Meson's default build type is `debug`: enable debugging symbols and disable optimization.
We anticipate having more _users_ than algorithm developers, so let's set the default build type to `release` so that users will run optimized (faster) builds by default.
For developers, documentation has been added to encourage them to set the build type to `debug` when developing.

feat: set default buildtype to `release`, controllable in `configure.py`

---

doc/setup.md
doc/troubleshooting.md

At the moment, if you build `iguana` with the _latest_ `fmt` from its main branch, it will say `fmt::join` does not exist. So, let's recommend to users that they should checkout a recent (hopefully stable) tag, rather than the most recent commit.
Eventually containerization will save us from this, or https://github.com/JeffersonLab/iguana/issues/59 will help enforce specific versions.

doc: recommend latest dependency tag rather than main branch

---

bind/python/iguana-example-00-basic.py
src/iguana/algorithms/clas12/EventBuilderFilter.cc
src/iguana/algorithms/clas12/EventBuilderFilter.h
src/iguana/algorithms/example/ExampleAlgorithm.cc
src/iguana/algorithms/example/ExampleAlgorithm.h

We have been keeping some additional unused banks, options, and logging printouts; these were originally for testing infrastructure development. We don't need 'em any more.

fix: remove unnecessary things from test algorithms

---

doc/setup.md

Don't suggest users to run `cmake` with `-j$(nproc)`, since `nproc` does not exist on macOS (use `sysctl -n hw.ncpu` instead); those are just _example_ `cmake` commands anyway.

doc: remove `nproc` suggestion

---

src/iguana/algorithms/TypeDefs.h
src/iguana/algorithms/clas12/LorentzTransformer.cc
src/iguana/algorithms/clas12/LorentzTransformer.h
src/iguana/algorithms/meson.build

This allows other algorithms to use these types, and the ability to define other common types.
@asligonulacar, for #85

fix: move Lorentz vector types to `iguana` namespace in common header

---

.github/install-dependency-packages.sh
.github/pages-index.html
.github/workflows/ci.yml
.github/workflows/macos.yml
.github/workflows/minver.yml
README.md
examples/meson.build
meson.build
meson.options
src/iguana/algorithms/clas12/LorentzTransformer.cc
src/iguana/algorithms/meson.build
src/iguana/tests/iguana-test.cc
src/iguana/tests/meson.build

Resolves #98 
First step toward #97

feat: test algorithms with sanitizers and coverage

---

.github/workflows/ci.yml
examples/build_with_cmake/CMakeLists.txt
examples/build_with_meson/meson.build
meson.build

Adds build option `static_hipo`, which if true, will link against static HIPO libraries.
- resolve #23 
- requires https://github.com/gavalian/hipo/pull/46

build: static link `hipo4`

---

.github/workflows/ci.yml
examples/meson.build

The examples have 0% coverage. This PR adds examples to `meson` tests, so that they are coverage tested.
The `test_examples` CI job will remain, since that one tests the _installed_ examples, whereas `meson test` tests the examples in the builddir; `test_examples` no longer has to test all the examples, just enough of them to give us confidence that the _installation_ is stable.

feat: test examples with `meson test`

---

.github/install-dependency-packages.sh
.github/workflows/ci.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/minver.yml

- use new 'physics' validation files (the same we use for physics timelines) and cache them
- cache `hipo` build, paving the way for caching ROOT builds

ci: cache test HIPO files and `hipo` build

---

.github/install-dependency-packages.sh
.github/schedule-issue.md
.github/source-ROOT.sh
.github/workflows/ci.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/minver.yml
bind/python/README.md
doc/maintenance.md
doc/setup.md
meson.build
meson.options
meson/minimum-version.sh
meson/resolve-dependencies.py
src/iguana/algorithms/Algorithm.cc
src/iguana/algorithms/Algorithm.h
src/iguana/tests/meson.build

- build and cache ROOT from source, since installing ROOT from `Homebrew` or `pacman` returns a package that `meson` cannot "find"; this gives us more control over the ROOT build anyway, in case someone needs non-default options
- rebuild HIPO and ROOT weekly on early Sunday mornings, so that the cached builds are up-to-date with respect to upstream
- drop `MinVer` workflow trigger on PRs, and leave it to the weekly runs; we don't need to check this one so often
- add `noROOT` build tests, to test for users who do not have ROOT

fix(ci): test ROOT-dependent algorithms

---

examples/build_with_meson/meson.build
meson.build

revert https://github.com/JeffersonLab/iguana/pull/74
fix: #111
Users may use `prefer_static` build option to control linking behavior.

build: revert static `hipo` link

---

meson/ifarm/README.md
meson/ifarm/ifarm.ini

@baltzell this adds the directory `meson/ifarm` with concise build directions and a native INI file with recommended build options. You're welcome to modify these as needed.

build: add native file for `ifarm` builds

---

bind/python/meson.build

fix: add executable permission for group and other for Python examples

---

src/iguana/algorithms/Algorithm.cc
src/iguana/algorithms/Algorithm.h
src/iguana/algorithms/AlgorithmBoilerplate.h
src/iguana/algorithms/AlgorithmFactory.cc
src/iguana/algorithms/example/ExampleAlgorithm.cc
src/iguana/algorithms/physics/InclusiveKinematics.cc

If an algorithm depends on some _new_ bank created by another algorithm, the user should be informed of the requirement. This PR requires registration of created banks, so that the lookup of which algorithm(s) create them can be performed.

feat: tell the user which algorithm(s) create new banks

---

.github/workflows/ci.yml

For retrying scheduled workflows, a 1-day retention time is too short.

ci: increase artifact rentention time

---

src/iguana/algorithms/Algorithm.cc
src/iguana/algorithms/Algorithm.h
src/iguana/algorithms/AlgorithmBoilerplate.h
src/iguana/algorithms/AlgorithmFactory.cc
src/iguana/algorithms/AlgorithmSequence.cc
src/iguana/algorithms/AlgorithmSequence.h
src/iguana/algorithms/Validator.cc
src/iguana/algorithms/Validator.h
src/iguana/services/ConfigFileReader.cc
src/iguana/services/ConfigFileReader.h
src/iguana/services/Logger.cc
src/iguana/services/Logger.h
src/iguana/services/Object.cc
src/iguana/services/Object.h
src/iguana/services/YAMLReader.cc
src/iguana/services/YAMLReader.h

This change is done where it is reasonable. For cases where the string is used for `unordered_map` lookup or insertion, `std::string const&` is used instead; when we move to C++20, then we can use heterogeneous lookup instead.

perf: replace `std::string const`-type parameters with `std::string_view`

---

.github/install-dependency-packages.sh
src/iguana/tests/include/TestLogger.h

Use older `meson` while awaiting for new release to fix #135 (since failing `iguana` tests currently prevent webpage deployment...)

ci: temporarly roll back to meson 1.3.2

---

.github/workflows/ci.yml
meson.build
src/iguana/algorithms/meson.build
src/iguana/services/meson.build

Example 02 was complaining about missing `libhipo4`, even though `dependency(hipo4)` was included in its executable. The issue is actually upstream of the executable: `libhipo4`'s location was never put in `install_rpath` of the shared libraries.

fix: add `hipo` to library rpaths

---

.github/install-dependency-packages.sh
.github/workflows/ci.yml
.github/workflows/minver.yml

Linux min-ver job fails since latest `doxygen` needs `fmt` 10.x; workaround by moving `doxygen` installation to job step.
Fix https://github.com/JeffersonLab/iguana/issues/160

fix(ci): only install `doxygen` when needed

---

examples/meson.build

If we process too many events in the example tests, the test log output file will be huge, since the examples are quite verbose by design. Users who want to run examples with more events may simply run the example executables (rather than `meson test`).

test: limit the number of events for example tests

---

.github/install-dependency-packages.sh
.github/workflows/ci.yml

Using Arch Linux Archive's `meson` version 1.3.2 is now failing (#181, #182). Let's revert to using the latest `meson` version now, and live with the sanitizer env var issue #135 until a new `meson` version is released.

fix(ci): revert to latest `meson` version

---

.github/workflows/linux.yml

#135 has been preventing documentation deployments; so, until `meson` 1.5 is available (which will fix this issue), let's just turn off `ubsan`.

ci: disable `ubsan` until `meson` 1.5

---

meson.build

Fixes the following `meson` error:
```
ERROR: pkgconfig.generate keyword argument "variables" empty variable value
```

fix: omit empty variables from pkg-config file generation

---

bind/python/iguana-example-00-basic.py
examples/iguana-example-00-basic.cc
src/iguana/algorithms/clas12/MomentumCorrection.cc
src/iguana/algorithms/clas12/MomentumCorrection.h
src/iguana/algorithms/clas12/MomentumCorrectionValidator.cc
src/iguana/algorithms/clas12/MomentumCorrectionValidator.h
src/iguana/algorithms/clas12/SectorFinder.cc
src/iguana/algorithms/clas12/SectorFinder.h
src/iguana/algorithms/meson.build
src/iguana/tests/iguana-test.cc
src/iguana/tests/include/TestAlgorithm.h
src/iguana/tests/meson.build

- `SectorFinder` now creates a new bank, with the sector for each particle
- since this is required for `MomentumCorrection`, the tests are now aware of prerequisite algorithms

feat: make `SectorFinder` a creator algorithm and a prerequisite for `MomentumCorrection`

---

.github/workflows/ci.yml
meson.options
src/iguana/tests/meson.build

We want the validator artifacts (validation plots) to be full statistics, so add build option `test_validator_all_stats` to do so. It's default is `false`, so that `meson test` is fast by default; validator devs should set it to `true` if they want to see full stats locally (or just leave that job to the CI).

ci: run validators on all available events

---

meson.build
meson/this_iguana.csh.in

Although many users use `tcsh` as the default shell, some may prefer `csh`. Since `csh` and `tcsh` iguana environments create a sub-shell, this fix provides the ability to spawn the preferred sub-shell, `tcsh` or `csh`.
Also removes a `meson` warning about empty configuration.

fix: support `csh` as well as `tcsh`

---

.github/workflows/linux.yml

ci: re-enable `ubsan`, since `meson` 1.4.1 has been released

---

.github/workflows/ci.yml
src/iguana/algorithms/Bindings.cc
src/iguana/algorithms/clas12/PhotonGBTFilter/Algorithm.cc
src/iguana/algorithms/clas12/PhotonGBTFilter/Algorithm.h

To prevent warnings (which can be real issues) from slipping through the cracks, build with `-werror`, so CI jobs fail if there are warnings. This is not the default build option, so that developers can still make test builds if there are warnings.
Fixed the following warnings:
- unused lambda captures in `PhotonGBTFilter`
- `sprintf` deprecation

fix: treat warnings as errors and fix them

---

examples/config/my_combined_config_file.yaml
examples/config/my_config_directory/algorithms/clas12/ZVertexFilter/Config.yaml
examples/config/my_z_vertex_cuts.yaml
examples/iguana_ex_fortran_01_action_functions.f
src/iguana/algorithms/clas12/ZVertexFilter/Algorithm.cc
src/iguana/algorithms/clas12/ZVertexFilter/Algorithm.h
src/iguana/algorithms/clas12/ZVertexFilter/Bindings.cc
src/iguana/algorithms/clas12/ZVertexFilter/Config.yaml
src/iguana/algorithms/clas12/ZVertexFilter/Validator.cc
src/iguana/algorithms/clas12/ZVertexFilter/Validator.h
src/iguana/algorithms/meson.build

Simple fix to add pids of particles for which to filter based on zvertex. Added default to only electrons in Config.yaml.
Also added validator to plot before and after zvertex cuts. This is plotted for electrons, on which we cut in the validator, but also other particles which shouldn't (and aren't) cut on.
Example plots for electrons and pions outputted by validator:

ZVertexFilter: Added option for pids and validator

---

examples/iguana_ex_fortran_01_action_functions.f
src/iguana/algorithms/clas12/ZVertexFilter/Algorithm.cc
src/iguana/algorithms/clas12/ZVertexFilter/Algorithm.h
src/iguana/algorithms/clas12/ZVertexFilter/Bindings.cc
src/iguana/algorithms/clas12/ZVertexFilter/Validator.cc

There is no z-vertex position from the FT, z vertex cut shouldn't be applied to electrons in the FT.
Fix is to require abs( status )>=2000 ie a particle is in FD or CD. Validator now only plots particles in FD or CD.

ZVertexFilter: Only cut on FD and CD particles

---

.github/install-dependency-packages.sh

Fix the 56 broken pipe errors, coming from a `brew` command:
```
[+] INSTALLING PACKAGE tree
==> Downloading https://ghcr.io/v2/homebrew/core/tree/manifests/2.1.2
==> Fetching tree
==> Downloading https://ghcr.io/v2/homebrew/core/tree/blobs/sha256:0fdd34e46049ad22f376d1a38e9ab0a546c8d73c2069a8facc871c9457bf23d8
==> Pouring tree--2.1.2.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/tree/2.1.2: 9 files, 181.6KB
Error: Broken pipe @ io_writev - <STDOUT>
Error: Broken pipe @ io_writev - <STDOUT>
```

fix(ci): brew errors `Broken pipe @ io_writev`

---

.github/workflows/ci.yml

No need to tell `meson` how to consume ROOT _twice_.

fix(ci): no need for meson argument `--cmake-prefix-path` since we already set `$CMAKE_PREFIX_PATH`

---

src/iguana/algorithms/clas12/FTEnergyCorrection/Algorithm.cc
src/iguana/algorithms/clas12/FTEnergyCorrection/Algorithm.h
src/iguana/algorithms/clas12/LorentzTransformer/Algorithm.cc
src/iguana/algorithms/clas12/LorentzTransformer/Algorithm.h
src/iguana/algorithms/clas12/MomentumCorrection/Algorithm.cc
src/iguana/algorithms/clas12/MomentumCorrection/Algorithm.h
src/iguana/algorithms/clas12/ZVertexFilter/Algorithm.cc
src/iguana/algorithms/clas12/ZVertexFilter/Algorithm.h
src/iguana/algorithms/physics/InclusiveKinematics/Algorithm.cc
src/iguana/algorithms/physics/InclusiveKinematics/Algorithm.h

C++ action function parameters should not be mutable.

fix: `const` parameters of action functions

---

src/iguana/algorithms/clas12/PhotonGBTFilter/Algorithm.h
src/iguana/algorithms/clas12/PhotonGBTFilter/Validator.cc

This is the last fix we need for #244. `PhotonGBTFilter` already applies this cut, so the validator needs to also apply this cut to the unfiltered photons.

fix: add FD cut for pre-filter photons in `PhotonGBTFilter` validator

---

src/iguana/algorithms/clas12/SectorFinder/Algorithm.cc
src/iguana/algorithms/clas12/SectorFinder/Algorithm.h
src/iguana/algorithms/clas12/SectorFinder/Config.yaml
src/iguana/algorithms/clas12/SectorFinder/Validator.cc
src/iguana/algorithms/clas12/SectorFinder/Validator.h
src/iguana/algorithms/meson.build

Before this pull request the config file was set up to take the same bank to find sector for charged and uncharged particles. This is problematic because the natural choice for charged particles (DC) is different from neutrals (calorimeters). SectorFinder also needed an action function and a validator
This pulls request introduces:
- Different banks for charged and neutral particles in config yaml. Choice is given to use default for one or both of charged/neutrals. Also fixed a bug due to certain banks containing non FD detectors, now only look at FD detectors.
- Add pindex entry to output bank to avoid confusion due to filtering of REC::Particle bank.
- Introduce a vector action function which finds the sector for a given pindex from a vector of sectors and pindices taken from some bank. …

Sector Finder: Support for charged & neutral particles, added action function and validator

---

.github/download-ROOT-source.rb
.github/install-dependency-packages.sh
.github/workflows/ci.yml
meson/minimum-version.sh

Issues this PR resolves:
- resolved by #250 by avoiding returning `std::tuple`

fix: test minimum and latest ROOT versions

---

meson/minimum-version.sh

`ifarm` has the following modules:
```
----------------------------------------- /scigroup/cvmfs/hallb/clas12/sw/modulefiles -----------------------------------------
root/6.30.04  root/6.32.02
----------------------------------------- /scigroup/cvmfs/scicomp/sw/el9/modulefiles ------------------------------------------
root/6.24.08-gcc11.4.0  root/6.28.10-gcc11.4.0  root/6.30.04-gcc11.4.0
root/6.26.14-gcc11.4.0  root/6.30.02-gcc11.4.0  root/6.30.06-gcc11.4.0
```
So `clas12` modules prefer 6.30+, but older ones are installed in `el9` modules.
I've been doing most of my local testing with 6.28.10, so let's decrease the `patch` version down a bit (before #264 we didn't care about the patch version, and just required 6.28+).
I don't really want to re-build ROOT locally (and my dependent …

build: decrease ROOT minimum version 6.28.12 -> 6.28.10

---

src/chameleon/chameleon

- `::exists?` methods have been removed from the standard, in favor of `::exist?`

fix(chameleon): compatibility with Ruby 3.2

---

.github/install-dependency-packages.sh
.github/workflows/ci.yml
meson/minimum-version.sh

The [Arch Linux Archive](https://wiki.archlinux.org/title/Arch_Linux_Archive), used in our minver tests, may sometimes be inaccessible; this PR allows for fallback to an alternate mirror when the main one fails.

fix(ci): fallback to alternate ALA mirror

---

.github/workflows/ci.yml

HIPO 4.2's build system will be Meson (https://github.com/gavalian/hipo/pull/59); this PR tests if Iguana can successfully consume it.

ci: HIPO 4.2.0 testing

---

examples/meson.build
meson.build
src/iguana/services/Logger.h

Workaround https://github.com/fmtlib/fmt/issues/4133 until fixed (so we can continue to use `-Werror` on CI here). Revert when fixed.
fixes #277

fix: workaround `-Wstringop-overflow` warnings from `fmt`

---

meson/this_iguana.sh.in

For example, this allows [`bass`](https://github.com/edc/bass) to work.

fix: handle wrapper arguments when sourcing `this_iguana.sh`

---

src/iguana/algorithms/Algorithm.h

This change allows users to get the index of a bank in a `hipo::banklist` using the name of the bank. Perhaps this feature could be upstreamed, but since `hipo::banklist` is just a type definition, I'm not sure where to put it exactly.

feat: change `Algorithm::GetBankIndex` to a public method

---

examples/config/my_combined_config_file.yaml
examples/config/my_config_directory/algorithms/clas12/ZVertexFilter/Config.yaml
examples/config/my_z_vertex_cuts.yaml
src/iguana/algorithms/Algorithm.cc
src/iguana/algorithms/Algorithm.h
src/iguana/algorithms/clas12/ZVertexFilter/Algorithm.cc
src/iguana/algorithms/clas12/ZVertexFilter/Config.yaml
src/iguana/services/YAMLReader.cc
src/iguana/services/YAMLReader.h

This allows an algorithm's YAML configuration to control the log level; `SetOption("log",...)` still takes the highest priority. For example:
```yaml
clas12::SomeAlgorithm:
log: trace
```

feat: set algorithm log levels from config `yaml` files

---

.github/workflows/ci.yml

Failing coverage tests have been preventing the documentation from being regenerated; disabling coverage testing until #282 is fixed.

fix: disable coverage test until fixed

---

.github/workflows/ci.yml
src/iguana/algorithms/Algorithm.cc
src/iguana/algorithms/Algorithm.h

- finding a bank is upstreamed: https://github.com/gavalian/hipo/pull/65
- reverts https://github.com/JeffersonLab/iguana/pull/299

refactor: use `hipo::getBanklistIndex` to get bank indices

---

src/iguana/algorithms/clas12/PhotonGBTFilter/Algorithm.h
src/iguana/algorithms/example/ExampleAlgorithm/Algorithm.h

In particular:
- `PhotonGBTFilter::Filter` is _not_ an action function, by definition
- `ExampleAlgorithm::Filter` _is_ an action function
cc. @dglazier, https://github.com/JeffersonLab/iguana/issues/310#issuecomment-2501641728

fix(doc): action functions must use `action_function` docstring, and non-action functions must not

---

meson/ubsan.supp

See https://github.com/gavalian/hipo/issues/49

fix: suppress all `hipo::structure` UBSan alignment errors

---

.github/install-dependency-packages.sh
.github/workflows/ci.yml
.github/workflows/linux.yml
meson.options
src/iguana/tests/meson.build

fixes #282 
coverage seems to fail only on multithreaded tests; opened as #316.

ci: re-enable coverage tests

---

src/iguana/services/Logger.h

`fmt` v11.1 is out.
reverts #278
closes #279

fix: revert workaround -Wstringop-overflow warnings from fmt

---

subprojects/rcdb/meson.build

Some package maintainers install `mariadb.pc`, and some install `libmariadb.pc`.

fix(build): check for `libmariadb` pkg-config

---

doc/maintenance.md
meson.build
meson/detect-version.sh
meson/release/install-cvmfs.sh

We've been using `detect-version.sh` to automatically get the version number from the most recent `git` tag, but this relies on the `git` metadata being available at build time. Since this may not always be true, especially in deployment / release builds, we want to avoid the situation of deploying `iguana.pc` with an unknown version number. We thus switch to using a static version number instead.
The only drawback is that we now need to remember to bump the version number prior to a release.

build: use static project version number

---

bind/python/requirements.txt

fixes https://github.com/JeffersonLab/iguana/issues/337
respects https://github.com/mfmceneaney/hipopybind/issues/3

fix(build): bump `hipopy` requirement, since CMake v4 has been released

---

.github/workflows/ci.yml

When the cache hits (which is pretty much always), it's much faster to just use the runner, rather than wait for the container image pull. The job will be about 4 seconds, rather than 1-3 minutes.

doc(ci): use Ubuntu runner, not container image, for downloading test data

---

bind/python/meson.build
doc/gen/mainpage.md
examples/meson.build
meson.build
meson/this_iguana.sh.in
src/iguana/algorithms/meson.build
src/iguana/bankdefs/meson.build

- fixes the case when there's another `iguana.pc` in `$PKG_CONFIG_PATH`, it was prioritizing that one
- `this_iguana.sh` now _overwrites_ the `$IGUANA_PREFIX_PATH`
- previous behavior appends, which does not allow `this_iguana.sh` to override some other (container) Iguana installation
- removes additional variables from `iguana.pc`, since nowadays we use (but not rely on) environment variable `$IGUANA`
- internally `$IGUANA` is not used, but we've been asked to provide it for consumers
- `this_iguana.sh` now _optionally_ includes dependency paths in path-type environment variables
- including them can be convenient at runtime, but also can be annoying in many cases
- let's make it optional for now, with the default keeping them included (no potentially breaking change)

fix(this_iguana.sh): prioritize Iguana in all path-type env vars

---

src/iguana/algorithms/clas12/SectorFinder/Algorithm.cc
src/iguana/algorithms/clas12/SectorFinder/Algorithm.h

Some downstream algorithms may still need sector info, so obtain sector for _all_ particles, not just the ones that were filtered out (use `.getRows()` rather than `.getRowList()`)

doc: explain why `SectorFinder` operates on all particles, and not just filtered particles

---

.github/workflows/ci.yml

GitHub actions does not respect custom image entrypoints. Our entrypoint in `container-forge` uses `hostname` to choose between on-site and off-site database URIs; the default is on-site, since we anticipate most production usage to be on-site (on `ifarm`).
Since the default is on-site, and GitHub runners are off-site, we force the usage of the off-site URI.

fix: force usage of off-site RCDB URI

---

.github/workflows/ci.yml
bind/python/iguana_ex_python_00_run_functions.py
bind/python/iguana_ex_python_01_action_functions.py
bind/python/iguana_ex_python_hipopy.py
examples/iguana_ex_cpp_00_run_functions.cc
examples/iguana_ex_cpp_01_action_functions.cc
examples/iguana_ex_cpp_dataframes.cc

closes #323 
- make the examples more complete, especially `00_run_functions`, regarding how to handle results
- make output of C++ and Python examples equivalent, and add a CI test for this

feat: demonstrate in examples how to handle algorithm results

---

examples/meson.build
meson.build
src/iguana/algorithms/meson.build
src/iguana/bindings/meson.build
src/iguana/tests/meson.build
subprojects/.gitignore

We are starting to see warnings such as
```
WARNING: Could not find and exact match for the CMake dependency ROOT.
However, Meson found the following partial matches:
['ROOT::Core', 'ROOT::vectorDict', 'ROOT::listDict', ...
Using imported is recommended, since this approach is less error prone
and better supported by Meson. Consider explicitly specifying one of
these in the dependency call with:
dependency('ROOT', modules: ['ROOT::<name>', ...])
Meson will now continue to use the old-style ROOT_LIBRARIES CMake
variables to extract the dependency information since no explicit
target is currently specified.
```
Let's do what it says, since now we can just use the `dependency` object in functions like `shared_library`, rather than manually adding ROOT's libraries and headers.
Tested against …

build: streamline ROOT dependency handling
